// Code generated by MockGen. DO NOT EDIT.
// Source: rocket.go
//
// Generated by this command:
//
//	mockgen -source=rocket.go -destination=mocks/mock_rocket_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ahernandez9/rockets/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRocketRepository is a mock of RocketRepository interface.
type MockRocketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRocketRepositoryMockRecorder
	isgomock struct{}
}

// MockRocketRepositoryMockRecorder is the mock recorder for MockRocketRepository.
type MockRocketRepositoryMockRecorder struct {
	mock *MockRocketRepository
}

// NewMockRocketRepository creates a new mock instance.
func NewMockRocketRepository(ctrl *gomock.Controller) *MockRocketRepository {
	mock := &MockRocketRepository{ctrl: ctrl}
	mock.recorder = &MockRocketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRocketRepository) EXPECT() *MockRocketRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockRocketRepository) FindAll(ctx context.Context) []*models.Rocket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*models.Rocket)
	return ret0
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRocketRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRocketRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockRocketRepository) FindByID(ctx context.Context, id string) (*models.Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRocketRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRocketRepository)(nil).FindByID), ctx, id)
}

// GetCount mocks base method.
func (m *MockRocketRepository) GetCount(ctx context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCount indicates an expected call of GetCount.
func (mr *MockRocketRepositoryMockRecorder) GetCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockRocketRepository)(nil).GetCount), ctx)
}

// Save mocks base method.
func (m *MockRocketRepository) Save(ctx context.Context, rocket *models.Rocket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rocket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRocketRepositoryMockRecorder) Save(ctx, rocket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRocketRepository)(nil).Save), ctx, rocket)
}
