// Code generated by MockGen. DO NOT EDIT.
// Source: rocket.go
//
// Generated by this command:
//
//	mockgen -source=rocket.go -destination=mocks/mock_rocket_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ahernandez9/rockets/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRocketService is a mock of RocketService interface.
type MockRocketService struct {
	ctrl     *gomock.Controller
	recorder *MockRocketServiceMockRecorder
	isgomock struct{}
}

// MockRocketServiceMockRecorder is the mock recorder for MockRocketService.
type MockRocketServiceMockRecorder struct {
	mock *MockRocketService
}

// NewMockRocketService creates a new mock instance.
func NewMockRocketService(ctrl *gomock.Controller) *MockRocketService {
	mock := &MockRocketService{ctrl: ctrl}
	mock.recorder = &MockRocketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRocketService) EXPECT() *MockRocketServiceMockRecorder {
	return m.recorder
}

// GetCount mocks base method.
func (m *MockRocketService) GetCount(ctx context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCount indicates an expected call of GetCount.
func (mr *MockRocketServiceMockRecorder) GetCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockRocketService)(nil).GetCount), ctx)
}

// GetRocket mocks base method.
func (m *MockRocketService) GetRocket(ctx context.Context, id string) (*models.Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRocket", ctx, id)
	ret0, _ := ret[0].(*models.Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRocket indicates an expected call of GetRocket.
func (mr *MockRocketServiceMockRecorder) GetRocket(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRocket", reflect.TypeOf((*MockRocketService)(nil).GetRocket), ctx, id)
}

// ListRockets mocks base method.
func (m *MockRocketService) ListRockets(ctx context.Context, sortBy string) ([]*models.Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRockets", ctx, sortBy)
	ret0, _ := ret[0].([]*models.Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRockets indicates an expected call of ListRockets.
func (mr *MockRocketServiceMockRecorder) ListRockets(ctx, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRockets", reflect.TypeOf((*MockRocketService)(nil).ListRockets), ctx, sortBy)
}

// UpdateRocket mocks base method.
func (m *MockRocketService) UpdateRocket(ctx context.Context, rocket *models.Rocket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRocket", ctx, rocket)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRocket indicates an expected call of UpdateRocket.
func (mr *MockRocketServiceMockRecorder) UpdateRocket(ctx, rocket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRocket", reflect.TypeOf((*MockRocketService)(nil).UpdateRocket), ctx, rocket)
}
